spring:
  security:
    user:
      name: admin
      password: admin

server:
  port: 5000

security:
  basic:
    enable: false

  jwt:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    expiration: 86400
    secret: JwtSecretKey

feign:
  client:
    config:
      default:
        readTimeout: 1500
        connectTimeout: 500
userData:
  service:
    base:
      url: http://localhost:5020
    name: userData

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
      hostname: ${HOSTNAME:localhost}