spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com

site:
  base:
    url:
      https: ${SITE_URL}

security:
  jwt:
    expiration: 3600
    secret: ${JWT_SECRET}

feign:
  client:
    config:
      default:
        readTimeout: 15000
        connectTimeout: 5000
userData:
  service:
    base:
      url: ${USER_DATA_SERVICE_URL}
    name: ${USRR_DATA_SERVICE_NAME}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI}
    instance:
      hostname: ${HOSTNAME}